"""Render sector-grouped suggestions as a Markdown report."""

from __future__ import annotations

from datetime import datetime, timezone

from .scoring import Suggestion
from .watchlist import Sector

DISCLAIMER = (
    "This report is generated by a rules-based heuristic for educational and "
    "informational purposes only. It is **not** licensed financial or "
    "investment advice, and no trades are placed automatically -- every "
    "suggestion is for you to evaluate and execute yourself, if at all. "
    "Markets involving early-stage themes (quantum computing, clean energy, "
    "frontier tech) can be highly volatile; do your own research and size "
    "positions accordingly."
)


def render_report(sector_suggestions: dict[Sector, list[Suggestion]]) -> str:
    generated_at = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")
    lines: list[str] = [
        "# Thematic Market Advisory Report",
        "",
        f"_Generated {generated_at}_",
        "",
        f"> {DISCLAIMER}",
        "",
    ]

    for sector, suggestions in sector_suggestions.items():
        lines.append(f"## {sector.name}")
        lines.append(f"_{sector.description}_ (benchmark: {sector.benchmark})")
        lines.append("")

        if not suggestions:
            lines.append("_No data available for this sector's tickers right now._")
            lines.append("")
            continue

        ranked = sorted(suggestions, key=lambda s: s.score, reverse=True)
        lines.append("| Ticker | Suggestion | Score | Key Signals |")
        lines.append("|---|---|---|---|")
        for suggestion in ranked:
            signals = "; ".join(suggestion.rationale[:3])
            lines.append(f"| {suggestion.ticker} | **{suggestion.label}** | {suggestion.score:+.0f} | {signals} |")
        lines.append("")

        for suggestion in ranked:
            lines.append(f"**{suggestion.ticker} -- {suggestion.label}** (score {suggestion.score:+.0f})")
            for note in suggestion.rationale:
                lines.append(f"- {note}")
            for note in suggestion.risk_notes:
                lines.append(f"- ⚠️ {note}")
            lines.append("")

    return "\n".join(lines)
